# Legendary effects seeded from R.O.L.L. (fallout76.wiki) — 142 effects
# Each entry: (name, description, star, categories_csv, legendary_modules, extra_components_json, acquisition_sources_json)

import json

LEGENDARY_EFFECTS = [
    # ─── 1-STAR (15 modules) ───────────────────────────────────────────────
    ("Adrenal",         "+10% damage per kill while on Kill Streak",                         1, "Armor,Power Armor,Weapon Ranged,Weapon Melee", 15, [{"item":"Adrenal Reaction Serum","qty":1}],         ["Bounty Hunting"]),
    ("Anti-armor",      "+50% Armor Penetration",                                            1, "Weapon Ranged,Weapon Melee",                   15, [{"item":"Black Titanium","qty":5}],                 []),
    ("Aristocrat's",    "Up to +50% damage based on Caps carried",                           1, "Armor,Power Armor,Weapon Ranged,Weapon Melee", 15, [{"item":"Bobblehead: Caps","qty":1}],               []),
    ("Assassin's",      "+50% damage to Humans",                                             1, "Armor,Power Armor,Weapon Ranged,Weapon Melee", 15, [{"item":"Liquid Courage","qty":1}],                 ["Gleaming Depths","Daily Ops"]),
    ("Auto Stim",       "Auto-revive with Stimpak at 25% health",                            1, "Armor,Power Armor",                            15, [{"item":"Stimpak","qty":5}],                        []),
    ("Berserker's",     "Up to +50% damage as DR decreases",                                 1, "Weapon Ranged,Weapon Melee",                   15, [{"item":"Psycho","qty":5}],                         []),
    ("Bloodied",        "Up to +130% damage as Health decreases",                            1, "Weapon Ranged,Weapon Melee",                   15, [{"item":"Adrenal Reaction Serum","qty":1}],         ["Gleaming Depths","Daily Ops"]),
    ("Bolstering",      "+35 Energy Resist/Damage Resist as Health decreases",               1, "Armor,Power Armor",                            15, [{"item":"Med-X","qty":5}],                          []),
    ("Chameleon",       "Invisibility while sneaking and not moving",                        1, "Armor,Power Armor",                            15, [{"item":"Chameleon Serum","qty":1}],                []),
    ("Cloaking",        "Invisibility on melee hit every 30s",                               1, "Armor,Power Armor",                            15, [{"item":"Stealth Boy","qty":1}],                    []),
    ("Executioner's",   "+50% damage when target is below 40% health",                      1, "Weapon Ranged,Weapon Melee",                   15, [{"item":"Leather","qty":25}],                       []),
    ("Exterminator's",  "+50% damage to Mirelurks and Insects",                              1, "Armor,Power Armor,Weapon Ranged,Weapon Melee", 15, [{"item":"Bloodbug Proboscis","qty":1},{"item":"Stinging Barb","qty":1}], []),
    ("Feral's",         "Faster feral meter transformation on kills",                        1, "Weapon Melee",                                 15, [{"item":"Black Titanium","qty":5}],                 ["Bounty Hunting"]),
    ("Furious",         "+5% damage per Onslaught stack (max 9 stacks)",                     1, "Weapon Ranged,Weapon Melee",                   15, [{"item":"Fury","qty":1}],                           ["Gleaming Depths","Daily Ops"]),
    ("Ghoul Slayer's",  "+50% damage to Ghouls",                                             1, "Armor,Power Armor,Weapon Ranged,Weapon Melee", 15, [{"item":"RadShield","qty":1}],                      []),
    ("Gourmand's",      "Up to +40% damage as hunger and thirst fill",                       1, "Weapon Ranged,Weapon Melee",                   15, [{"item":"Vegetarian Ham","qty":1}],                 []),
    ("Heavyweight",     "-90% armor weight",                                                 1, "Armor",                                        15, [{"item":"Bird Bones Serum","qty":1}],               []),
    ("Hunter's",        "+50% damage to Animals",                                            1, "Armor,Power Armor,Weapon Ranged,Weapon Melee", 15, [{"item":"Yao Guai Hide","qty":1}],                  []),
    ("Instigating",     "+50% damage when target is above 60% health",                      1, "Weapon Ranged,Weapon Melee",                   15, [{"item":"Whiskey","qty":5}],                        []),
    ("Juggernaut's",    "Up to +100% damage as Health increases",                            1, "Weapon Ranged,Weapon Melee",                   15, [{"item":"Buffout","qty":5}],                        ["Gleaming Depths"]),
    ("Junkie's",        "Up to +100% damage per addiction",                                  1, "Weapon Ranged,Weapon Melee",                   15, [{"item":"Mentats","qty":5}],                        []),
    ("Life Saving",     "50% chance to auto-revive with Stimpak on death",                   1, "Armor",                                        15, [{"item":"Stimpak","qty":5}],                        []),
    ("Lucid",           "+40% weapon damage as feral meter fills",                           1, "Armor,Power Armor,Weapon Ranged,Weapon Melee", 15, [{"item":"Bobblehead: Medicine","qty":1}],           ["Bounty Hunting"]),
    ("Medic's",         "Heals friendly targets for 5% of damage dealt per hit",             1, "Weapon Ranged,Weapon Melee",                   15, [{"item":"Bobblehead: Medicine","qty":1}],           ["Daily Ops"]),
    ("Mutant Slayer's", "+50% damage to Super Mutants",                                      1, "Armor,Power Armor,Weapon Ranged,Weapon Melee", 15, [{"item":"Super Mutant Head","qty":1}],              []),
    ("Mutant's",        "+50% damage per active mutation",                                   1, "Armor,Power Armor,Weapon Ranged,Weapon Melee", 15, [{"item":"Asbestos","qty":10}],                      []),
    ("Nocturnal",       "+50% damage while cloaked or at night",                             1, "Armor,Power Armor,Weapon Ranged,Weapon Melee", 15, [{"item":"Nuclear Material","qty":10}],              ["Daily Ops"]),
    ("Overeater's",     "+6% DR as hunger and thirst fill",                                  1, "Armor,Power Armor",                            15, [{"item":"Perfect Bubblegum","qty":1}],              []),
    ("Quad",            "+300% ammo capacity",                                               1, "Weapon Ranged",                                15, [{"item":"Fusion Core","qty":1}],                    ["Daily Ops"]),
    ("Regenerating",    "+0.5% health regen per second",                                     1, "Armor,Power Armor",                            15, [{"item":"Healing Factor Serum","qty":1}],           []),
    ("Sniper's",        "+100% damage to distant targets",                                   1, "Weapon Ranged",                                15, [{"item":"Bobblehead: Perception","qty":1}],         ["Bounty Hunting"]),
    ("Stalker's",       "+100% sneak attack damage",                                         1, "Weapon Ranged",                                15, [{"item":"Calmex","qty":1}],                         []),
    ("Suppressor's",    "Reduces target's damage output by 25% for 5s on hit",               1, "Weapon Ranged,Weapon Melee",                   15, [{"item":"Grounded Serum","qty":1}],                 []),
    ("Troubleshooter's","+50% damage to Robots",                                             1, "Armor,Power Armor,Weapon Ranged,Weapon Melee", 15, [{"item":"Circuitry","qty":10}],                     ["Daily Ops","Gleaming Depths"]),
    ("Two Shot",        "Fires an additional projectile, +75% damage",                       1, "Weapon Ranged",                                15, [{"item":"Lead","qty":20}],                          ["Nuka-World Season"]),
    ("Unyielding",      "+3 to all S.P.E.C.I.A.L. stats at low health",                     1, "Armor",                                        15, [{"item":"X-Cell","qty":5}],                         []),
    ("Vampire's",       "Restore 2% max health over 2 seconds per hit",                      1, "Weapon Ranged,Weapon Melee",                   15, [{"item":"Blood Pack","qty":10}],                    ["Gleaming Depths","Daily Ops"]),
    ("Vanguard's",      "+35 Energy Resist/Damage Resist as Health increases",               1, "Armor,Power Armor",                            15, [{"item":"Blood Pack","qty":5}],                     []),
    ("Zealot's",        "+50% damage to Scorched",                                           1, "Armor,Power Armor,Weapon Ranged,Weapon Melee", 15, [{"item":"Ultracite","qty":10}],                     []),

    # ─── 2-STAR (30 modules) ───────────────────────────────────────────────
    ("Agility",         "+2 Agility",                                                        2, "Armor,Power Armor",                            30, [{"item":"Bobblehead: Agility","qty":1}],            []),
    ("Antiseptic",      "+25% reduced disease chance from environmental hazards",            2, "Armor,Power Armor",                            30, [{"item":"Disease Cure","qty":10}],                  []),
    ("Basher's",        "+50% bash damage",                                                  2, "Weapon Ranged",                                30, [{"item":"Concrete","qty":25}],                      ["Gleaming Depths"]),
    ("Charisma",        "+2 Charisma",                                                       2, "Armor,Power Armor",                            30, [{"item":"Bobblehead: Charisma","qty":1}],           []),
    ("Crippling",       "+50% limb damage",                                                  2, "Weapon Ranged,Weapon Melee",                   30, [{"item":"Black Titanium","qty":5}],                 ["Raid plans"]),
    ("Elementalist",    "Increase all resistances by 5",                                     2, "Armor,Power Armor",                            30, [{"item":"Bobblehead: Endurance","qty":1}],          ["Bounty Hunting"]),
    ("Endurance",       "+2 Endurance",                                                      2, "Armor,Power Armor",                            30, [{"item":"Bobblehead: Endurance","qty":1}],          []),
    ("Explosive",       "Projectiles explode for +20% weapon damage",                        2, "Weapon Ranged",                                30, [{"item":"Bobblehead: Explosive","qty":1}],          []),
    ("Fierce",          "Fortify limb resistance based on Kill Streak count",                 2, "Armor,Power Armor",                            30, [{"item":"Bobblehead: Strength","qty":1}],           ["Bounty Hunting"]),
    ("Fireproof",       "+25 Fire Resistance",                                               2, "Armor,Power Armor",                            30, [{"item":"Floater Flamer Pus Sac","qty":10}],        []),
    ("Glutton",         "Hunger and Thirst grow 10% slower",                                 2, "Armor,Power Armor",                            30, [{"item":"Perfect Bubblegum","qty":1}],              []),
    ("Hardy",           "Receive 7% less explosion damage",                                  2, "Armor,Power Armor",                            30, [{"item":"Bobblehead: Explosive","qty":1}],          []),
    ("HazMat",          "+25 Radiation Resistance",                                          2, "Armor,Power Armor",                            30, [{"item":"Rad-X","qty":10}],                         []),
    ("Heavy Hitter's",  "+40% power attack damage",                                          2, "Weapon Melee",                                 30, [{"item":"Concrete","qty":25}],                      ["Daily Ops"]),
    ("Hitman's",        "+25% damage while aiming",                                          2, "Weapon Ranged",                                30, [{"item":"Fiber Optics","qty":10}],                  ["Daily Ops"]),
    ("Inertial",        "Replenish 15 Action Points with each kill",                         2, "Weapon Ranged,Weapon Melee",                   30, [{"item":"Canned Coffee","qty":10}],                 ["Gleaming Depths"]),
    ("Intelligence",    "+2 Intelligence",                                                   2, "Armor,Power Armor",                            30, [{"item":"Bobblehead: Intelligence","qty":1}],       []),
    ("Last Shot",       "Last round has 25% chance to deal +100% damage",                   2, "Weapon Ranged",                                30, [{"item":"Gunpowder","qty":15}],                     []),
    ("Luck",            "+2 Luck",                                                           2, "Armor,Power Armor",                            30, [{"item":"Bobblehead: Luck","qty":1}],               []),
    ("Pain Killer",     "Gain Health over time while on Kill Streak",                        2, "Armor,Power Armor",                            30, [{"item":"Bobblehead: Medicine","qty":1}],           ["Bounty Hunting"]),
    ("Perception",      "+2 Perception",                                                     2, "Armor,Power Armor",                            30, [{"item":"Bobblehead: Perception","qty":1}],         []),
    ("Pick Pocketer's", "Target kills have 50% chance to grant 1-4 Caps",                   2, "Weapon Melee",                                 30, [{"item":"Bobblehead: Caps","qty":1}],               ["Bounty Hunting"]),
    ("Poisoner's",      "+25 Poison Resistance",                                             2, "Armor,Power Armor",                            30, [{"item":"Floater Gnasher Pus Sac","qty":10}],       []),
    ("Powered",         "+5% Action Point regen",                                            2, "Armor,Power Armor",                            30, [{"item":"Canned Coffee","qty":10}],                 []),
    ("Rapid",           "+25% ranged attack speed, +40% melee attack speed",                 2, "Weapon Ranged,Weapon Melee",                   30, [{"item":"Speed Demon Serum","qty":1}],              ["Raid plans","Stamps"]),
    ("Riposting",       "+50% melee damage reflection while blocking",                       2, "Weapon Melee",                                 30, [{"item":"Glass","qty":25}],                         []),
    ("Rushing",         "Gain Action Points over time while on Kill Streak",                 2, "Armor,Power Armor",                            30, [{"item":"Bobblehead: Agility","qty":1}],            ["Bounty Hunting"]),
    ("Steady",          "+25% melee damage while not moving",                                2, "Weapon Melee",                                 30, [{"item":"Orange Mentats","qty":3}],                 []),
    ("Strength",        "+2 Strength",                                                       2, "Armor,Power Armor",                            30, [{"item":"Bobblehead: Strength","qty":1}],           []),
    ("V.A.T.S. Enhanced","+50% chance to hit in V.A.T.S.",                                  2, "Weapon Ranged",                                30, [{"item":"Berry Mentats","qty":3}],                  ["Daily Ops"]),
    ("Vital",           "+50% critical hit damage",                                          2, "Weapon Ranged,Weapon Melee",                   30, [{"item":"Eagle Eyes Serum","qty":1}],               ["Gleaming Depths"]),
    ("Warming",         "+25 Cryo Resistance",                                               2, "Armor,Power Armor",                            30, [{"item":"Floater Freezer Pus Sac","qty":10}],       []),

    # ─── 3-STAR (60 modules) ───────────────────────────────────────────────
    ("Acrobat's",       "-50% fall damage",                                                  3, "Armor",                                        60, [{"item":"Marsupial Serum","qty":1}],                []),
    ("Active",          "Max AP increased by +20",                                           3, "Armor,Power Armor",                            60, [{"item":"Bobblehead: Agility","qty":1}],            ["Bounty Hunting"]),
    ("Adamantium",      "Receive 15% less limb damage",                                      3, "Armor",                                        60, [{"item":"Twisted Muscles Serum","qty":1}],          []),
    ("Agility (Wpn)",   "+3 Agility",                                                        3, "Weapon Ranged,Weapon Melee",                   60, [{"item":"Bobblehead: Agility","qty":1}],            []),
    ("Arms Keeper's",   "Weapon weights reduced by 20%",                                     3, "Armor,Power Armor",                            60, [{"item":"Bobblehead: Small Guns","qty":1}],         []),
    ("Barbarian",       "+1 STR per kill on Kill Streak (max 10)",                           3, "Weapon Melee",                                 60, [{"item":"Bobblehead: Melee","qty":1}],              ["Bounty Hunting"]),
    ("Belted",          "Ammo weight reduced by 20%",                                        3, "Armor,Power Armor",                            60, [{"item":"Lead","qty":25}],                          []),
    ("Blocker",         "+15% more damage blocked",                                          3, "Weapon Melee",                                 60, [{"item":"Oil","qty":10}],                           []),
    ("Burning",         "5% chance to deal 12 Fire damage/sec for 3s to attackers",         3, "Armor,Power Armor",                            60, [{"item":"Floater Flamer Pus Sac","qty":15}],        []),
    ("Cavalier's",      "-5% damage taken while sprinting",                                  3, "Armor,Power Armor",                            60, [{"item":"Oil","qty":10}],                           ["Daily Ops"]),
    ("Charisma (Wpn)",  "+3 Charisma",                                                       3, "Weapon Ranged,Weapon Melee",                   60, [{"item":"Bobblehead: Charisma","qty":1}],           []),
    ("Defender's",      "-15% blocked damage; -40% power attack damage received",            3, "Armor,Power Armor,Weapon Melee",               60, [{"item":"Steel","qty":25}],                         ["Raid"]),
    ("Dissipating",     "+0.25% radiation damage recovery per second",                       3, "Armor,Power Armor",                            60, [{"item":"RadAway","qty":10}],                       []),
    ("Diver's",         "Breathe underwater",                                                3, "Armor",                                        60, [{"item":"Plastic","qty":15}],                       []),
    ("Doctor's",        "+5% effectiveness of Stimpaks, RadAway, and Rad-X",                3, "Armor,Power Armor",                            60, [{"item":"Stimpak: Super","qty":1}],                 []),
    ("Durability",      "Breaks 50% slower",                                                 3, "Armor,Power Armor,Weapon Ranged,Weapon Melee", 60, [{"item":"Bobblehead: Repair","qty":1}],             []),
    ("Electrified",     "5% chance to deal 12 Energy damage/sec for 3s to attackers",       3, "Armor,Power Armor",                            60, [{"item":"Electrically Charged Serum","qty":1}],     []),
    ("Endurance (Wpn)", "+3 Endurance",                                                      3, "Weapon Ranged,Weapon Melee",                   60, [{"item":"Bobblehead: Endurance","qty":1}],          []),
    ("Frozen",          "5% chance to deal 12 Cryo damage/sec for 4s to attackers",         3, "Armor,Power Armor",                            60, [{"item":"Floater Freezer Pus Sac","qty":15}],       []),
    ("Ghost's",         "10% chance to become invisible for 2s when hitting a target",       3, "Weapon Ranged",                                60, [{"item":"Stealth Boy","qty":1}],                    ["Raid"]),
    ("Glowing",         "Kills increase Glow/Rads (20 RADs for humans)",                     3, "Weapon Ranged,Weapon Melee",                   60, [{"item":"Bobblehead: Science","qty":1}],            ["Bounty Hunting"]),
    ("Healthy",         "Max HP increased by +20",                                           3, "Armor,Power Armor",                            60, [{"item":"Bobblehead: Endurance","qty":1}],          ["Bounty Hunting"]),
    ("Intelligence (Wpn)","+3 Intelligence",                                                 3, "Weapon Ranged,Weapon Melee",                   60, [{"item":"Bobblehead: Intelligence","qty":1}],       []),
    ("Lightweight",     "-90% item weight",                                                  3, "Weapon Ranged,Weapon Melee",                   60, [{"item":"Cork","qty":10}],                          ["Raid","Season"]),
    ("Luck (Wpn)",      "+3 Luck",                                                           3, "Weapon Ranged,Weapon Melee",                   60, [{"item":"Bobblehead: Luck","qty":1}],               []),
    ("Lucky",           "+15 bonus V.A.T.S. critical charge",                                3, "Weapon Ranged,Weapon Melee",                   60, [{"item":"Bobblehead: Luck","qty":1}],               ["Raid"]),
    ("Nimble",          "+100% faster movement speed while aiming",                          3, "Weapon Ranged",                                60, [{"item":"Springs","qty":25}],                       ["Raid"]),
    ("Pack Rat's",      "Junk item weights reduced by 20%",                                  3, "Armor,Power Armor",                            60, [{"item":"Marsupial Serum","qty":1}],                []),
    ("Perception (Wpn)","+3 Perception",                                                     3, "Weapon Ranged,Weapon Melee",                   60, [{"item":"Bobblehead: Perception","qty":1}],         ["Daily Ops"]),
    ("Reflex",          "2% evade chance",                                                   3, "Armor,Power Armor",                            60, [{"item":"Bobblehead: Agility","qty":1}],            ["Bounty Hunting"]),
    ("Resilient",       "+500 damage resistance while reloading",                            3, "Weapon Ranged",                                60, [{"item":"Med-X","qty":5}],                          ["Raid"]),
    ("Safecracker's",   "+1 lockpicking skill, +1 hacking skill",                            3, "Armor,Power Armor",                            60, [{"item":"Bobblehead: Lock Picking","qty":1}],       []),
    ("Secret Agent's",  "+25% less noise while sneaking, -25% detection chance",             3, "Armor",                                        60, [{"item":"Bobblehead: Sneak","qty":1}],              []),
    ("Sentinel's",      "-5% damage taken while not moving",                                 3, "Armor,Power Armor",                            60, [{"item":"Scaly Skin Serum","qty":1}],               []),
    ("Steadfast",       "+50 damage resistance while aiming",                                3, "Weapon Ranged",                                60, [{"item":"Ballistic Fiber","qty":5}],                ["Raid plans","Season plans"]),
    ("Strength (Wpn)",  "+3 Strength",                                                       3, "Weapon Ranged,Weapon Melee",                   60, [{"item":"Bobblehead: Strength","qty":1}],           ["Daily Ops"]),
    ("Swift",           "+15% reload speed",                                                 3, "Weapon Ranged",                                60, [{"item":"Speed Demon Serum","qty":1}],              ["Raid"]),
    ("Thru-hiker's",    "Food, drink, and chem weights reduced by 20%",                      3, "Armor,Power Armor",                            60, [{"item":"Purified Water","qty":10}],                []),
    ("Toxic",           "5% chance to deal 12 Poison damage/sec for 7s to attackers",        3, "Armor,Power Armor",                            60, [{"item":"Floater Gnasher Pus Sac","qty":15}],       []),
    ("V.A.T.S. Optimized","-35% action point cost in V.A.T.S.",                             3, "Weapon Ranged,Weapon Melee",                   60, [{"item":"Sugar","qty":10}],                         ["Daily Ops"]),

    # ─── 4-STAR (120 modules, Gleaming Depths) ────────────────────────────
    ("Aegis",           "Fortifies Phys/Energy Resists +50, Poison/Cryo/Fire +20 for wearer & teammates within 50ft", 4, "Power Armor",                    120, [{"item":"Circuitry","qty":5}],                      ["Gleaming Depths Stage 3"]),
    ("Battle-Loader's", "15% chance to instantly reload when bashing (up to 75% on full stack)",                       4, "Armor,Power Armor",              120, [{"item":"Talons Serum","qty":1}],                   ["Gleaming Depths Stage 2"]),
    ("Bruiser's",       "Melee weapons deal +5% bonus damage (up to +25% on full stack)",                              4, "Armor,Power Armor",              120, [{"item":"Bufftats","qty":1}],                       ["Gleaming Depths Stage 4"]),
    ("Bully's",         "+25% damage per crippled limb the target has",                                                4, "Weapon Ranged,Weapon Melee",     120, [{"item":"Buffout","qty":1}],                        ["Gleaming Depths Stage 1"]),
    ("Charged",         "Light attacks build up charge released with heavy attack (max 3 charges)",                    4, "Weapon Melee",                   120, [{"item":"Fusion Core","qty":3}],                    ["Gleaming Depths Stage 3"]),
    ("Choo-Choo's",     "10% chance for 500 damage and Bloody Mess when sprinting into targets (up to 50%)",           4, "Power Armor",                    120, [{"item":"Cannonballs","qty":15}],                   ["Gleaming Depths Stage 3"]),
    ("Combo-Breaker's", "When dealing damage, 50% chance to not use AP (10% for auto melee)",                          4, "Weapon Melee",                   120, [{"item":"Day Tripper","qty":1}],                    ["Gleaming Depths Stage 3"]),
    ("Conductor's",     "Critical hits restore 10 Health & AP instantly and 100 more over 5s for you and teammates",   4, "Weapon Ranged,Weapon Melee",     120, [{"item":"Pure Crimson Flux","qty":5}],              ["Gleaming Depths Stage 3"]),
    ("Electrician's",   "When reloading, emit a shock wave that stuns nearby targets for 3 seconds",                   4, "Weapon Ranged",                  120, [{"item":"Bobblehead: Energy Weapons","qty":1}],     ["Gleaming Depths Stage 2"]),
    ("Encircler's",     "+10% damage for each combat target around you (up to +50%)",                                  4, "Weapon Ranged,Weapon Melee",     120, [{"item":"Overdrive","qty":1}],                      ["Gleaming Depths Stage 4"]),
    ("Fencer's",        "+12.5% melee damage; +12.5% per nearby teammate (up to +50% with full team)",                 4, "Weapon Melee",                   120, [{"item":"Bobblehead: Melee","qty":1}],              ["Gleaming Depths Stage 2"]),
    ("Fracturer's",     "When crippling limbs, they explode dealing up to 50 explosion damage to nearby targets",      4, "Weapon Ranged,Weapon Melee",     120, [{"item":"Gunpowder","qty":25}],                     ["Gleaming Depths Stage 1"]),
    ("Icemen's",        "Applies Cryo on hit that slows targets when dealing damage in V.A.T.S.",                      4, "Weapon Melee",                   120, [{"item":"Pure Fluorescent Flux","qty":5}],          ["Gleaming Depths Stage 4"]),
    ("Limit-Breaking",  "Each worn armor piece reduces critical hit cost by -10% (up to -50% on full stack)",          4, "Armor,Power Armor",              120, [{"item":"Pure Violet Flux","qty":5}],               ["Gleaming Depths Stage 5"]),
    ("Miasma's",        "When hit, a poisonous DoT cloud harms nearby targets for 10s",                                4, "Armor,Power Armor",              120, [{"item":"Plague Walker Serum","qty":1}],             ["Gleaming Depths Stage 4"]),
    ("Pin-Pointer's",   "+20% weak spot damage",                                                                       4, "Weapon Ranged",                  120, [{"item":"Formula P","qty":1}],                      ["Gleaming Depths Stage 1"]),
    ("Polished",        "Greater equipped item condition increases weapon damage (up to +60% at 100% condition)",       4, "Weapon Ranged,Weapon Melee",     120, [{"item":"Improved Repair Kit","qty":1}],             ["Gleaming Depths Stage 4"]),
    ("Pounder's",       "+10% damage per Onslaught stack, +10 max Onslaught stacks",                                   4, "Weapon Melee",                   120, [{"item":"Fury","qty":1}],                           ["Gleaming Depths Stage 3"]),
    ("Propelling",      "Movement and sprint speed increased by +5% (up to +25% on full stack)",                       4, "Power Armor",                    120, [{"item":"Vault Steel Scrap","qty":15}],             ["Gleaming Depths Stage 5"]),
    ("Pyromaniac's",    "When a combat target is burning, deal +50% bonus damage",                                     4, "Weapon Ranged,Weapon Melee",     120, [{"item":"Asbestos","qty":15}],                      ["Gleaming Depths Stage 5"]),
    ("Radioactive-Powered","AP regen +2 per RAD (up to +10 AP on full stack)",                                         4, "Power Armor",                    120, [{"item":"Pure Cobalt Flux","qty":5}],               ["Gleaming Depths Stage 1"]),
    ("Ranger's",        "Ranged weapons deal +5% bonus damage (up to +25% on full stack)",                             4, "Armor,Power Armor",              120, [{"item":"Psychobuff","qty":1}],                     ["Gleaming Depths Stage 4"]),
    ("Reflective",      "Return 10% of damage received back toward enemy (up to 50% on full stack)",                   4, "Power Armor",                    120, [{"item":"Bobblehead: Science","qty":1}],             ["Gleaming Depths Stage 3"]),
    ("Rejuvenator's",   "Gradually restores wearer's and nearby teammates' Health and AP within 50ft",                 4, "Power Armor",                    120, [{"item":"Stimpak Diffuser","qty":5}],               ["Gleaming Depths Stage 2"]),
    ("Runner's",        "Sprinting AP cost reduced by -20% (up to -100% on full stack)",                               4, "Armor,Power Armor",              120, [{"item":"Purified Water","qty":10}],                ["Gleaming Depths Stage 1"]),
    ("Sawbones's",      "Health regenerates slowly (+1 Health/s; up to +5 Health/s on full stack)",                    4, "Armor,Power Armor",              120, [{"item":"Healing Factor Serum","qty":1}],            ["Gleaming Depths Stage 5"]),
    ("Scanner's",       "V.A.T.S. attack AP cost reduced by -5% (up to -25% on full stack)",                          4, "Power Armor",                    120, [{"item":"X-Cell","qty":1}],                         ["Gleaming Depths Stage 1"]),
    ("Stabilizer's",    "Improves weapon recoil and stability by 50%",                                                 4, "Weapon Ranged",                  120, [{"item":"Rubber","qty":25}],                        ["Gleaming Depths Stage 2"]),
    ("Stalwart's",      "Power Armor breaks 5% slower for owner and teammates within 50ft (up to 25%)",                4, "Power Armor",                    120, [{"item":"Bobblehead: Leader","qty":1}],             ["Gleaming Depths Stage 5"]),
    ("Tanky's",         "+200 DR for 10s when standing still, 20s cooldown (up to +1000 on full stack)",               4, "Armor,Power Armor",              120, [{"item":"Ballistic Fiber","qty":5}],                ["Gleaming Depths Stage 2"]),
    ("Thrill-Seeker's", "+3% Melee Speed and +3% Reload Speed per Kill Streak stack (max 30% each)",                   4, "Weapon Ranged,Weapon Melee",     120, [{"item":"Adrenal Reaction Serum","qty":1}],         []),
    ("Viper's",         "When a combat target is poisoned, deal +50% bonus damage",                                    4, "Weapon Ranged,Weapon Melee",     120, [{"item":"Acid","qty":15}],                          ["Gleaming Depths Stage 5"]),
]


def as_insert_tuples():
    """Return list of tuples ready for INSERT INTO legendary_effects."""
    return [
        (
            name, desc, star, cats,
            modules,
            json.dumps(comps),
            json.dumps(sources),
        )
        for name, desc, star, cats, modules, comps, sources in LEGENDARY_EFFECTS
    ]
